#!/bin/sh

if [ $# -eq 0 ]; then
	rsync -P --exclude='*.xcf.bz2' -lr . drydencafe@mail.simonstl.com:public_html/drydencafe/
else
	rsync -P --exclude='*.xcf.bz2' -lr $* drydencafe@mail.simonstl.com:public_html/drydencafe/
fi
